name: test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test go fmt
        run: test -z $(go fmt ./...)
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          only-new-issues: true
      - name: Test coverage
        run: go test -covermode atomic -coverprofile='profile.cov' ./...
      - name: Send coverage
        if: runner.os == 'Linux'
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
